Update filePath regex replace to account for font hashes
Elhebert/laravel-mix-sri pull request #39
Opened 2021-11-01 09:02 UTC by bram-pkg

2021-11-03 08:59 UTC, Elhebert requested changes
The current change are not compatible with Laravel Mix cache busting feature.

2021-11-03 08:59 UTC, Elhebert commented on src/SriPlugin.ts
> +          filePath = filePath.replace(/\?\w{32}/, '')
This will break the Laravel Mix cache busting feature as it won't remove the `?id=` part.

Something like this would be better:
```suggestion
          filePath = filePath.replace(/\?(\w{32}|id=\w{20})/, '')
```

2021-11-03 09:00 UTC, bram-pkg commented on src/SriPlugin.ts
> +          filePath = filePath.replace(/\?\w{32}/, '')
It will still replace the id= part too, the regexes are just on two separate lines now. Your solution is cleaner though.

2021-11-08 09:24 UTC, Elhebert commented
#41 should solve the issue by filtering the "third party" assets out.

2021-11-08 09:24 UTC, closed without merging

2021-11-08 11:27 UTC, bram-pkg commented
Thanks man!